bridges:
  slack: "@slackbot:hacklab.fi"
bridge_timeout: 10.0
link_previews: false
hello:
  html: "Viestisi käsittelee ihminen, ja vastaaminen voi kestää <strong>muutamia päiviä</strong>.<br><br>Your responses will be handled by a human. Please note that responses may take a <strong>few days</strong>."
tokens:
